language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install pipenv flake8
  - make init

# command to run tests
script:
  - make test-all
  - flake8 --max-line-length=99 .
